[build]
       command = "npm run build"
       publish = "public"

     [[headers]]
       for = "/*"
       [headers.values]
         Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' https://*.firebase.com https://*.googleapis.com https://*.gstatic.com https://*.cloudflare.com https://*.netlify.app https://cdn.jsdelivr.net https://cdn-cgi.netlify.app; object-src 'none'; connect-src 'self' https://*.googleapis.com https://*.firebaseio.com wss://*.firebaseio.com https://www.google-analytics.com /api/bible/*; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; frame-src 'self' https://*.netlify.app;"
         X-Frame-Options = "DENY"
         X-Content-Type-Options = "nosniff"
         Referrer-Policy = "strict-origin-when-cross-origin"

     [[headers]]
       for = "/cdn-cgi/*"
       [headers.values]
         Content-Type = "application/javascript"

     [[redirects]]
       from = "/api/bible/*"
       to = "https://bible-api.com/:splat"
       status = 200
       force = true
       headers = { Access-Control-Allow-Origin = "*" }

     [[redirects]]
       from = "/*"
       to = "/index.html"
       status = 200