[build]
       command = "npm run build"
       publish = "public"

     [[redirects]]
       from = "/api/bible/*"
       to = "https://bible-api.com/:splat"
       status = 200
       force = true
       headers = { Access-Control-Allow-Origin = "*" }

     [[redirects]]
       from = "/*"
       to = "/index.html"
       status = 200