[build]
  base = "."
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "/index.js"
  to = "/index.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200